# ansible-playbook -i hosts app-updates.yml --limit prod
#
#   -i            = hosts file
#   -l            = limit to one host out of 
#   --check       = Dry run

---
- hosts: ilo

  vars_prompt:
    - name: "ansible_sudo_pass"
      prompt: "Sudo password"
      private: yes

  tasks:
    - name: Test connection
      ping:

    - name: Install default apps
      apt: pkg={{ item }} state=latest
      with_items:
        - aptitude
        - bash-completion
        - curl
        - git
        - openssh-client
        - openssh-server
        - open-vm-tools
        - wget
        - vim
      become: true
    
    - name: Update and upgrade all apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day
      become: true

    - name: Upgrade distribtuion
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: verify if a reboot is required after upgrade
      stat: path=/var/run/reboot-required1
      register: reboot_required
    
    - debug:
        msg: "Reboot required, rebooting..."
      when: reboot_required.stat.exists
      